### PR TITLE
optionally dont require PASSWORD_STORE_DIR

### PR DESCRIPTION
**Pull request by leohemsted**
it's often set in people's zshrc/equivalents

### CODE REVIEW

**Review by samuelhwilliams — APPROVED** [review]

**Comment by samuelhwilliams** [comment]
Although I thought our standard env var was `NOTIFY_CREDENTIALS` 🤔

**Comment by leohemsted** [comment]
hmmm looks like i've just set both for ease

```❯ cat ~/.zshrc | grep credentials
export NOTIFY_CREDENTIALS=~/dev/credentials
export PASSWORD_STORE_DIR=~/dev/credentials```

**Comment by samuelhwilliams** [comment]
I might vaguely prefer reading `NOTIFY_CREDENTIALS` since that's more explicitly the _correct_ credential store, as opposed to any generic `pass` directory

**Comment by leohemsted** [comment]
@samuelhwilliams good point. i've updated PR to first look at `NOTIFY_CREDENTIALS`, then `PASSWORD_STORE_DIR`, then it'll prompt the user if neither is set. i've tested this briefly and it seems to work fine

**Review by samuelhwilliams — APPROVED** [review]
👌

**Pull request merged**
